#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/nlp
  
  rm -rf build/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ nlp tests/test_sentencizer.py setup.py
else
  echo "DEV_BASE is not defined"
fi
