[meta]
version = "0.1.0"

[project]
name = "nlp"
package = "nlp"
main_lang = "py"
version = "0.0.16"
version_date = "2017-12-17"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
description = "some natural language processing (NLP) tools"
copyright = "2016-2017"
dev_status = "pre_alpha"
license = "mit"
relpath = "py/nlp"
state = "shared"
url = "https://jddixon.github.io/nlp"

[py]
packages = [ "nlp",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib",]
requirements = [ "nltk", "setuptools",]
test_requirements = []
